collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

#source: ./src

#destination: ./public

sass:
  sass_dir: assets/_sass
  style: compressed

exclude: [
  src,
  node_modules,
  package.json,
  package-lock.json,
  rollup.config.js,
  webpack.config.js,
  Gemfile,
  Gemfile.lock,
  assets/_sass,
  assets/_js,
  example
]

title: '@pix8/UI Accordion'
#logo: /assets/img/logo.png
logo: /assets/img/pixie-dust.gif
description: A simple JavaScript Accordion with a simple objective.
show_downloads: true
google_analytics:

repository: pix8/ui-accordion
#theme: jekyll-theme-minimal